# Generated by Django 4.1.9 on 2023-07-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('contactNo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(blank=True, max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('houseNo', models.CharField(max_length=10)),
                ('streetName', models.CharField(max_length=50)),
                ('localityName', models.CharField(max_length=50)),
                ('cityName', models.CharField(max_length=20)),
                ('countryName', models.CharField(max_length=20)),
                ('pinCode', models.IntegerField()),
                ('userPhoto', models.ImageField(blank=True, upload_to='UserPhoto')),
            ],
        ),
        migrations.CreateModel(
            name='PassportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_on_id', models.CharField(max_length=50)),
                ('last_name_on_id', models.CharField(max_length=50)),
                ('gender_on_id', models.CharField(max_length=6)),
                ('dob_on_id', models.DateField()),
                ('country_on_id', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('KYC_verified', models.BooleanField(default=False)),
                ('contactNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(max_length=100)),
                ('identity_card_image', models.ImageField(upload_to='Passport_img')),
                ('contactNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
